stages:
  data_ingestion:
    cmd: python -m src.components.data_ingestion
    deps:
      - src/components/data_ingestion.py
    outs:
      - artifacts/train.csv
      - artifacts/test.csv

  data_transformation:
    cmd: python -m src.components.data_transformation
    deps:
      - src/components/data_transformation.py
      - artifacts/train.csv # Depends on the output of the previous stage
      - artifacts/test.csv  # Depends on the output of the previous stage
    outs:
      - artifacts/proprocessor.pkl

  train:
    cmd: python -m src.components.model_trainer
    deps:
      - src/components/model_trainer.py
      - artifacts/proprocessor.pkl # Depends on the output of the previous stage
    outs:
      - artifacts/model.pkl